#ifndef LANG_H
#define LANG_H

enum OPTIONS
{
    INPUT_LANG_FILE_OPTION,
    INPUT_TREE_FILE_OPTION,
    OUTPUT_TREE_FILE_OPTION,
    OUTPUT_ASM_FILE_OPTION,
    OUTPUT_LANG_FILE_OPTION,
    HELP_OPTION,
    TREE_TO_LANG_COMPILE_OPTION,
    LANG_TO_TREE_COMPILE_OPTION,
    LANG_TO_ASM_COMPILE_OPTION,
    N_OPTIONS
};

extern const Option EXEC_OPTIONS[];
extern const size_t N_EXEC_OPTIONS;

#endif  // LANG_H
